(function() {
  const dict = {
    en: {
      brandName: "Vancouver TCM & Acupuncture Clinic",
      brandTag: "Acupuncture • TCM • Minimal, premium care in Vancouver, BC",
      navHome: "Home",
      navServices: "Services",
      navBooking: "Booking",
      svcIntroT: "How we choose what’s right for you",
      svcIntroP: "We start with an assessment, then select the most suitable combination—never “more is better.”",
      svcIntroLi1: "Pattern‑based assessment (symptoms + lifestyle + recovery)",
      svcIntroLi2: "Choose tools: acupuncture, manual therapy, adjuncts, (herbs as appropriate)",
      svcIntroLi3: "Simple home plan to support results between visits",
      svcAdjT: "Adjuncts (as needed)",
      svcAdjP: "Often paired with acupuncture/manual therapy when appropriate.",
      svcAdj1: "Cupping",
      svcAdj1s: "Tension & circulation support",
      svcAdj2: "Gua Sha",
      svcAdj2s: "Fascia tightness & fatigue",
      svcAdj3: "Moxibustion",
      svcAdj3s: "Cold pattern support (as appropriate)",
      svcAdj4: "Herbal consult",
      svcAdj4s: "Stage‑based support (after assessment)",
      svcCtaT: "Not sure what to book?",
      svcCtaP: "Choose “New Patient / First‑visit” and we’ll guide the next steps.",
      aboutTitle: "About",
      aboutLead: "In Vancouver, we make TCM clearer—and more practical.",
      aboutH1: "About us",
      aboutP1: "We believe great TCM is more than prescribing—it’s understanding your system over time. We focus on pattern differentiation: identify the drivers, then choose acupuncture/manual therapy/herbal support/moxibustion as appropriate, paired with simple lifestyle guidance to help you return to steadier energy and resilience.",
      aboutB1: "Whole‑person view",
      aboutB1s: "Not just a symptom—sleep, digestion, stress, recovery capacity all matter.",
      aboutB2: "Personalized, not generic",
      aboutB2s: "Same ‘back pain’ can have different drivers; treatment should match the pattern.",
      aboutB3: "Sustainable improvements",
      aboutB3s: "We give simple home steps you can actually do between visits.",
      aboutH2: "What to expect",
      aboutP2: "First visit is typically 60–75 minutes: assessment, treatment, and a short home plan. Follow‑ups refine and progress‑track.",
      aboutLi1: "Clear explanation of options and safety considerations",
      aboutLi2: "Comfort‑first technique, adjusted to sensitivity",
      aboutLi3: "Strict sanitation and sterile single‑use needles",
      aboutLi4: "Insurance receipts available (coverage depends on your plan)",
      aboutCtaT: "Book a first visit — get the right plan",
      aboutCtaS: "More than a one‑off treatment: a recovery path that fits your body. If you’re unsure what’s best, start with a first‑visit assessment and we’ll guide next steps.",
      aboutG1: "Reception & waiting",
      aboutG1s: "Quiet check‑in and a moment to slow down.",
      aboutG2: "Private rooms",
      aboutG2s: "Privacy‑minded spaces for focused care.",
      aboutG3: "Treatment area",
      aboutG3s: "Comfort‑first setup with clear safety steps.",
      tcmTitle: "Why choose us",
      tcmIntro: "We keep it clear: assess first, treat safely, then give you simple home guidance.",
      tcmLi1: "Pattern‑based care: tailored to your constitution and symptoms",
      tcmLi2: "Fits North American life: sleep, stress, and routines you can follow",
      tcmLi3: "Transparent plan: goals, frequency, expectations, and home steps",
      tcmBtn: "View services & pricing",
      concernsTitle: "Start here",
      concernsIntro: "New patient? Choose a first‑visit assessment. You can also view the clinic space and FAQ.",
      cx1: "First‑visit assessment",
      cx1s: "60–75 min: assessment + treatment + plan",
      cx2: "Clinic photos",
      cx2s: "Reception / rooms / treatment area (placeholders)",
      cx3: "FAQ",
      cx3s: "What to prepare, timeline, comfort, insurance",
      cx4: "Directions & parking",
      cx4s: "Location and arrival tips",
      navAbout: "About",
      navGallery: "Clinic Photos",
      navFAQ: "FAQ",
      navContact: "Contact",
      navPrivacy: "Privacy",
      heroKicker: "Whole‑person Traditional Chinese Medicine + modern lifestyle guidance (Vancouver, BC)",
      heroTitle: "Vancouver TCM Clinic — Personalized, pattern‑based care",
      heroLead: "We’re a Vancouver‑based TCM clinic focused on personalized, step‑by‑step care. Whether it’s fatigue, stress‑related insomnia, neck/back discomfort, digestive issues, or women’s health support, we start with your constitution and lifestyle—then build a clear, doable plan so progress is visible and sustainable.",
      heroBtn1: "Book First‑Visit Assessment",
      heroBtn2: "Explore Services",
      heroBadge1: "Insurance receipts",
      heroBadge2: "Single‑use sterile needles",
      heroBadge3: "Bilingual (中文/English)",
      heroGlassTitle: "Detailed and individualized care",
      heroGlassText: "Acupuncture · Herbal Medicine · Tui Na",
      homeCardTitle: "Home",
      homeCardIntro: "We provide individualized care through acupuncture, herbal medicine, and Traditional Chinese Medicine therapies based on each patient’s constitution and current condition, helping the body gradually return to balance.",
      homeCardLi1: "Support for pain conditions, neck, shoulder, waist, and back discomfort",
      homeCardLi2: "Support for digestion, skin, immunity, sleep, and stress-related concerns",
      homeCardLi3: "Treatment plans tailored to constitution, symptoms, and recovery stage",
      homeCardBtn: "View Services",
      bannerTitle: "First visit? Start here.",
      bannerText: "60–75 min assessment + treatment. We’ll outline a simple, measurable plan.",
      bannerPill: "New patients welcome",
      s1Title: "Core care",
      s1Sub: "Designed for real life—clear, safe, effective.",
      c1Title: "Acupuncture",
      c1Text: "Pain relief, nervous system regulation, and recovery support.",
      c1Li1: "Neck/shoulder/back pain",
      c1Li2: "Headache & migraine",
      c1Li3: "Stress & sleep",
      c2Title: "Cupping & Gua Sha",
      c2Text: "Muscle tension release and circulation support.",
      c2Li1: "Tight fascia & soreness",
      c2Li2: "Post‑workout recovery",
      c2Li3: "Fatigue",
      c3Title: "Women’s Health",
      c3Text: "Gentle cycle support and hormonal wellbeing.",
      c3Li1: "PMS & cramps",
      c3Li2: "Fertility support (as appropriate)",
      c3Li3: "Perimenopause support",
      s2Title: "Why patients choose us",
      s2aTitle: "Minimal, premium environment",
      s2aText: "Clean, calm, professional—privacy‑minded rooms and a modern feel.",
      s2bTitle: "Clear plan, measurable progress",
      s2bText: "We track what matters (pain, sleep, function) and adjust step by step.",
      s2cTitle: "Safety first",
      s2cText: "Sterile single‑use needles, strict sanitation, contraindication screening.",
      quote: "“Professional, calm, and effective. The plan was simple—and it worked.”",
      quoteBy: "— Example patient",
      ctaTitle: "Ready to feel better?",
      ctaText: "Pick a time online—or call us if you need help choosing the right appointment.",
      ctaBtn: "Book Now",
      footerAbout: "About",
      footerAboutText: "Modern integrative TCM care in Vancouver, BC—pattern‑based assessment, clear plans, safety‑first practice.",
      footerClinic: "Clinic",
      footerQuick: "Quick links",
      footerHours: "Hours (example)",
      footerH1: "Mon/Wed: 10:00–18:00",
      footerH2: "Tue/Thu: 12:00–20:00",
      footerH3: "Sat: 10:00–16:00",
      footerH4: "Sun: Closed",
      bookingTitle: "Booking",
      bookingLead: "Use the embedded scheduler below. If you prefer, open booking in a new tab.",
      bookingOpenTab: "Open booking in a new tab",
      bookingEmbedNote: "Embedded scheduler placeholder. Replace BOOKING_URL in README.txt with your Jane/Calendly link.",
      servicesTitle: "Services & Pricing",
      servicesLead: "Transparent pricing and safe combinations. Replace with your real packages.",
      svcP1Title: "New Patient (60–75 min)",
      svcP1Sub: "Assessment + treatment",
      svcP1Price: "$125–$165 (example)",
      svcP1Li1: "Health history & goals",
      svcP1Li2: "Acupuncture / adjuncts",
      svcP1Li3: "Simple home plan",
      svcP2Title: "Follow‑up (45–60 min)",
      svcP2Sub: "Progress tracking",
      svcP2Price: "$95–$135 (example)",
      svcP2Li1: "Re‑assessment",
      svcP2Li2: "Adjustments",
      svcP2Li3: "Guidance",
      svcP3Title: "Tuina / Manual therapy (45–60 min)",
      svcP3Sub: "Soft‑tissue support",
      svcP3Price: "$95–$145 (example)",
      svcP3Li1: "Neck/shoulder/back",
      svcP3Li2: "Recovery",
      svcP3Li3: "Stretching tips",
      contactTitle: "Contact",
      contactLead: "Address, map, and the easiest ways to reach us.",
      contactCard1: "Clinic info",
      contactAddressLabel: "Address:",
      contactPhoneLabel: "Phone:",
      contactEmailLabel: "Email:",
      contactCard2: "Parking & access",
      contactParkingText: "Replace this with your real parking and access instructions (e.g., street parking, paid lot, buzzer info).",
      contactMapTip: "Tip: Google Maps → Share → Embed a map.",
      privacyTitle: "Privacy",
      privacyLead: "A simple privacy statement you can customize.",
      galleryTitle: "Clinic Photos",
      galleryLead: "A calm, minimalist space focused on privacy and comfort. Below are placeholders—swap in your real photos before launch.",
      galleryC1Title: "Reception & waiting",
      galleryC1Text: "A quiet check‑in and a moment to slow down.",
      galleryC2Title: "Private rooms",
      galleryC2Text: "Privacy‑minded treatment rooms for focused care.",
      galleryC3Title: "Acupuncture / therapy area",
      galleryC3Text: "Comfort‑first setup with clear safety steps.",
      galleryC4Title: "Herbal consultation",
      galleryC4Text: "Explain the “why” and the “how” in plain language.",
      faqTitle: "FAQ",
      faqLead: "Quick answers to common questions. For personalized guidance, start with a first‑visit assessment.",
      faqQ1: "What should I prepare for my first visit?",
      faqA1: "Bring any recent reports if you have them. Wear comfortable clothing and share your main concerns, timeline, and goals.",
      faqQ2: "When will I feel changes?",
      faqA2: "It varies. Some feel relaxation or sleep improvements within a few visits; chronic concerns often need a short plan plus lifestyle steps.",
      faqQ3: "Does it hurt?",
      faqA3: "Most people feel mild sensations (dull ache, warmth, heaviness) or relaxation. We adjust to your comfort.",
      faqQ4: "Do you offer service in English?",
      faqA4: "Yes—bilingual support (中文/English) where available.",
      privH1: "What we collect",
      privP1: "We may collect contact details you voluntarily provide (name, phone, email) when you book or contact us.",
      privH2: "Third‑party services",
      privP2: "Online booking may be handled by third‑party platforms (e.g., Jane / Calendly). Their privacy policies apply.",
      privNote: "Replace this page with your clinic’s legal privacy policy as required.",
    },
    zh: {
      brandName: "温哥华中医针灸诊所",
      brandTag: "针灸 · 推拿理疗 · 中药调理 · 极简高端 · Vancouver, BC",
      faqCtaP: "Book a first‑visit assessment and we’ll guide the next steps.",
      faqCtaT: "Not sure if it’s right for you?",
      p5s: "After improvement, optional maintenance and prevention.",
      p5: "Maintenance",
      p4s: "Adjust based on feedback and measurable progress.",
      p4: "Treatment & follow‑up",
      p3s: "Set goals, visit frequency, and home steps.",
      p3: "Plan",
      p2s: "Review your concern, history, lifestyle; tongue/pulse as appropriate.",
      p2: "Assessment",
      p1s: "Book online or by phone—new or follow‑up visit.",
      p1: "Booking",
      processLead: "A clear, step‑by‑step visit experience.",
      processTitle: "How it works",
      svcO6: "Lifestyle guidance: food, sleep, stress routines, mobility and breathing",
      svcO5: "Herbal medicine: stage‑based support after assessment, with follow‑up adjustments",
      svcO4: "Cupping / Gua Sha: tension and fatigue support (as appropriate)",
      svcO3: "Moxibustion: warming support for cold patterns and recovery (as appropriate)",
      svcO2: "Tuina / manual therapy: for muscle/fascia tightness, limited mobility, desk‑related strain",
      svcO1: "Acupuncture: regulate pain, tension, sleep, and function—tailored to your goals",
      svcOverviewP: "A typical Vancouver TCM clinic offering—customize to your actual services.",
      svcOverviewT: "Service overview",
      atm5s: "Convenient access (example). Great for quick visits between work and family.",
      atm5: "Neighborhood & parking",
      atm4s: "We explain the “why” and “how” in plain language.",
      atm4: "Herbal consultation",
      atm3s: "Comfort‑first setup with clear safety steps.",
      atm3: "Acupuncture / therapy area",
      atm2s: "Private rooms for focused care and comfort.",
      atm2: "Treatment rooms",
      atm1s: "Quiet, clean space to downshift before treatment.",
      atm1: "Reception & waiting",
      aboutNote: "Note: These are common focus areas. Your plan is based on an individual assessment.",
      aboutF5: "Low immunity/fatigue, cold hands/feet, slow recovery",
      aboutF4: "Women’s health: cycle support, PMS, fertility support, postpartum recovery",
      aboutF3: "Digestive issues: bloating, reflux, irregularity",
      aboutF2: "Neck/shoulder tightness, desk‑related back pain, injury recovery",
      aboutF1: "Stress‑related insomnia, light sleep, anxiety tension",
      aboutFocusP: "In a fast‑paced city, many concerns come from long‑term overuse and under‑recovery. Common reasons patients visit include:",
      aboutFocusT: "What we often help with",
      aboutPh3s: "We prioritize home steps you can actually do: routines, mobility, food, and stress habits.",
      aboutPh3: "Sustainable",
      aboutPh2s: "The same ‘insomnia’ or ‘back pain’ can have different patterns—plans should match you.",
      aboutPh2: "Personalized",
      aboutPh1s: "We look beyond one symptom—sleep, digestion, stress, circulation, recovery capacity.",
      aboutPh1: "Whole‑person view",
      aboutPhiloT: "Our philosophy: Whole‑person, Personal, Sustainable",
      navHome: "首页",
      navServices: "服务与价格",
      navBooking: "预约",
      svcIntroT: "我们如何选择方案",
      svcIntroP: "先评估再治疗：根据体质与诱因选择合适组合，并在开始前与您确认。不是“越多越好”，而是“更适合你更重要”。",
      svcIntroLi1: "辨证思路：症状 + 生活方式 + 恢复力整体评估",
      svcIntroLi2: "按需选工具：针灸、推拿理疗、辅助项目（必要时中药咨询）",
      svcIntroLi3: "给到可执行的居家要点，帮助巩固效果",
      svcAdjT: "辅助项目（按需搭配）",
      svcAdjP: "常与针灸/推拿组合使用，以安全与适应症为前提。",
      svcAdj1: "拔罐",
      svcAdj1s: "紧张与局部循环支持",
      svcAdj2: "刮痧",
      svcAdj2s: "筋膜紧张与疲劳感",
      svcAdj3: "艾灸",
      svcAdj3s: "寒湿与虚弱支持（视情况）",
      svcAdj4: "中药咨询",
      svcAdj4s: "分阶段调理（需评估）",
      svcCtaT: "不确定预约哪项？",
      svcCtaP: "直接选择“首次评估”，我们会给出清晰建议与下一步计划。",
      aboutTitle: "关于我们",
      aboutLead: "在温哥华，把“中医”做得更清楚、更可落地。",
      aboutH1: "关于我们",
      aboutP1: "我们相信，好的中医不只是“开方”，更是对身体系统的理解与长期管理。我们坚持以辨证为核心：先分清寒热虚实、脏腑相关与诱因，再选择适合你的针灸/推拿理疗/草药/艾灸等方式，并配合简洁实用的生活建议，帮助你把身体状态一步步拉回到更稳定、更有能量的区间。",
      aboutB1: "整体观",
      aboutB1s: "不只看一个症状，也看睡眠、消化、压力与恢复力。",
      aboutB2: "因人而异",
      aboutB2s: "同样的腰痛/失眠，诱因与体质可能不同，方案也应不同。",
      aboutB3: "可持续",
      aboutB3s: "治疗之外，更重视你在家能做到的关键小步骤。",
      aboutH2: "首次就诊会发生什么",
      aboutP2: "首次通常 60–75 分钟：沟通评估 + 治疗 + 居家要点。复诊会根据反应追踪与调整。",
      aboutLi1: "治疗前说明目标、可选方案与注意事项",
      aboutLi2: "舒适度优先，按敏感度调整手法与强度",
      aboutLi3: "严格消毒与一次性无菌针具规范",
      aboutLi4: "可提供保险收据（是否覆盖以计划为准）",
      aboutCtaT: "预约初诊｜咨询适合的治疗方案",
      aboutCtaS: "我们希望你在这里得到的，不只是一次治疗，而是一套更懂你身体的“恢复路径”。如果你不确定自己适合哪种治疗方式，欢迎先预约初诊评估，我们会给出清晰建议与可执行计划。",
      aboutG1: "前台与等候区",
      aboutG1s: "办理手续、简短沟通，先把节奏慢下来。",
      aboutG2: "独立诊疗室",
      aboutG2s: "保护隐私，减少干扰，更专注。",
      aboutG3: "针灸/理疗区",
      aboutG3s: "舒适度优先，清晰的安全步骤。",
      tcmTitle: "首页三栏优势",
      tcmIntro: "我们把中医做得更清楚：先评估，再治疗，再给到你能坚持的居家建议。",
      tcmLi1: "辨证施治：四诊合参，针对体质与症状制定方案",
      tcmLi2: "更适合北美生活：把饮食、作息、压力管理写进可执行计划",
      tcmLi3: "治疗透明清晰：目标、频率、预期变化与居家建议更明确",
      tcmBtn: "查看服务与价格",
      concernsTitle: "从这里开始",
      concernsIntro: "第一次来？建议选择“初诊评估”。如果你还在犹豫，可以先看看诊所环境与常见问题。",
      cx1: "预约初诊评估",
      cx1s: "60–75 分钟：评估 + 治疗 + 居家计划",
      cx2: "查看诊所环境",
      cx2s: "前台/诊疗室/理疗区（示例图）",
      cx3: "了解常见问题",
      cx3s: "准备什么？多久见效？是否疼？保险？",
      cx4: "路线与停车信息",
      cx4s: "地址、交通与到访提示",
      navAbout: "关于我们",
      navGallery: "诊所环境",
      navFAQ: "常见问题",
      navContact: "联系",
      navPrivacy: "隐私",
      heroKicker: "在温哥华，我们以传统中医整体观为核心，结合现代生活方式建议",
      heroTitle: "温哥华中医诊所｜以辨证为本的个性化调理与理疗",
      heroLead: "昆仑中医 The Origin TCM Clinic 提供专业传统中医诊疗服务，关注疼痛、消化、皮肤、免疫、睡眠与情志调理。我们以针灸、中药及传统中医疗法为基础，根据个人体质与当下状态提供个体化方案，帮助身体逐步恢复平衡、协调与稳定。在温哥华湿润多变的气候与现代生活节奏之下，许多不适往往彼此牵连、反复出现；我们希望以更细致、稳妥的方式，为每位来诊者提供贴合实际状态的调理支持。",
      heroBtn1: "预约初诊评估",
      heroBtn2: "了解服务项目",
      heroBadge1: "可提供保险收据",
      heroBadge2: "一次性无菌针具",
      heroBadge3: "中英双语服务",
      heroGlassTitle: "细致而个体化的调理",
      heroGlassText: "针灸 · 中药 · 推拿",
      homeCardTitle: "Home",
      homeCardIntro: "我们以针灸、中药及传统中医疗法为基础，根据个人体质与当下状态，提供个体化调理方案，帮助身体逐步恢复平衡。",
      homeCardLi1: "关注各类痛症、颈肩腰背不适",
      homeCardLi2: "关注消化、皮肤、免疫、睡眠与压力相关问题",
      homeCardLi3: "根据体质、症状与恢复阶段制定个体化方案",
      homeCardBtn: "查看服务",
      bannerTitle: "第一次来？从这里开始",
      bannerText: "初诊 60–75 分钟：了解主诉与生活习惯，进行舌脉等评估，制定清晰计划。",
      bannerPill: "新患者欢迎",
      s1Title: "核心服务",
      s1Sub: "更贴近北美生活方式——清晰、安全、有效。",
      c1Title: "针灸",
      c1Text: "缓解疼痛、调节神经系统、支持恢复。",
      c1Li1: "颈肩腰背痛",
      c1Li2: "头痛/偏头痛",
      c1Li3: "压力与睡眠",
      c2Title: "拔罐 & 刮痧",
      c2Text: "放松紧张肌肉与筋膜，支持循环与恢复。",
      c2Li1: "筋膜紧张与酸痛",
      c2Li2: "运动后恢复",
      c2Li3: "疲劳感",
      c3Title: "女性健康",
      c3Text: "以温和方式支持周期与激素健康。",
      c3Li1: "经期不适/PMS",
      c3Li2: "备孕支持（视情况）",
      c3Li3: "围绝经期支持",
      s2Title: "为什么选择我们",
      s2aTitle: "极简高端环境",
      s2aText: "干净安静、注重隐私，流程专业更安心。",
      s2bTitle: "计划清晰，可衡量进步",
      s2bText: "关注疼痛、睡眠、功能等指标，随访调整。",
      s2cTitle: "安全第一",
      s2cText: "一次性无菌针具、严格消毒、禁忌症筛查。",
      quote: "“整体很专业也很舒服，方案简单清晰，而且真的有效。”",
      quoteBy: "— 示例患者",
      ctaTitle: "准备开始变好吗？",
      ctaText: "在线选择时间；不确定预约类型也可以电话咨询。",
      ctaBtn: "立即预约",
      footerAbout: "关于",
      footerAboutText: "温哥华 Vancouver, BC 中医/针灸服务：辨证评估，计划清晰，安全优先。",
      footerClinic: "诊所信息",
      footerQuick: "快速入口",
      footerHours: "营业时间（示例）",
      footerH1: "周一/周三：10:00–18:00",
      footerH2: "周二/周四：12:00–20:00",
      footerH3: "周六：10:00–16:00",
      footerH4: "周日：休息",
      bookingTitle: "预约",
      bookingLead: "下方为预约嵌入。如果你更习惯新窗口打开，也可以点击按钮。",
      bookingOpenTab: "新窗口打开预约",
      bookingEmbedNote: "预约组件占位：在 README.txt 中替换 BOOKING_URL 为你的 Jane/Calendly 链接。",
      servicesTitle: "服务与价格",
      servicesLead: "定价透明、组合安全。你可以替换成真实套餐与价格。",
      svcP1Title: "首次评估（60–75 分钟）",
      svcP1Sub: "评估 + 治疗",
      svcP1Price: "$125–$165（示例）",
      svcP1Li1: "健康史与目标设定",
      svcP1Li2: "针灸/辅助项目（按需）",
      svcP1Li3: "居家建议（睡眠/拉伸/作息）",
      svcP2Title: "复诊（45–60 分钟）",
      svcP2Sub: "追踪与调整",
      svcP2Price: "$95–$135（示例）",
      svcP2Li1: "阶段性复盘",
      svcP2Li2: "方案调整",
      svcP2Li3: "简短指导",
      svcP3Title: "推拿理疗（45–60 分钟）",
      svcP3Sub: "软组织与筋膜支持",
      svcP3Price: "$95–$145（示例）",
      svcP3Li1: "颈肩腰背/臀腿",
      svcP3Li2: "久坐劳损/运动恢复",
      svcP3Li3: "拉伸要点",
      contactTitle: "联系",
      contactLead: "地址、地图与最方便的联系方式。",
      contactCard1: "诊所信息",
      contactAddressLabel: "地址：",
      contactPhoneLabel: "电话：",
      contactEmailLabel: "邮箱：",
      contactCard2: "交通与停车",
      contactParkingText: "请替换为真实的停车与进门说明（例如街边停车、付费停车场、门禁/门铃等）。",
      contactMapTip: "小提示：Google Maps → 分享 → 嵌入地图。",
      privacyTitle: "隐私",
      privacyLead: "一份可按需修改的简洁隐私声明。",
      galleryTitle: "诊所环境",
      galleryLead: "前台、诊疗室、针灸/理疗区与草药咨询（占位展示，上线前可替换为真实照片）。",
      galleryC1Title: "前台与等候区",
      galleryC1Text: "安静、干净、节奏放慢的空间，让身体先从“紧绷”状态松下来。",
      galleryC2Title: "诊疗室",
      galleryC2Text: "独立诊室保护隐私，治疗过程更专注、更安心。",
      galleryC3Title: "针灸/理疗区",
      galleryC3Text: "注重温度与舒适度，配合呼吸放松与体位调整，让体验更友好。",
      galleryC4Title: "草药与配方咨询",
      galleryC4Text: "用更容易理解的方式讲清楚配方目的、服用方法与注意事项。",
      faqTitle: "常见问题",
      faqLead: "把你最关心的先讲清楚。若需要个性化建议，建议从初诊评估开始。",
      faqQ1: "第一次来需要准备什么？",
      faqA1: "建议带上近期检查报告（如有），并提前想好主要困扰与持续时间；穿着宽松更方便治疗。",
      faqQ2: "多久能感觉到变化？",
      faqA2: "因人而异。有些问题会在几次内感觉放松与睡眠改善；慢性问题通常需要一段时间的连续治疗与生活调整。",
      faqQ3: "会不会很痛？",
      faqA3: "多数人感觉是轻微酸胀、麻或放松感；我们会根据敏感度调整手法与强度。",
      faqQ4: "你们提供英文服务吗？",
      faqA4: "我们可提供英文沟通（如适用）。",
      privH1: "我们收集什么",
      privP1: "当你预约或联系我们时，我们可能收集你自愿提供的联系信息（姓名、电话、邮箱等）。",
      privH2: "第三方服务",
      privP2: "在线预约可能由第三方平台（如 Jane / Calendly）提供，其隐私政策适用。",
      privNote: "请根据你的诊所合规要求，用正式隐私政策替换本页内容。",
    }
  };

  const LS_KEY = "lang_pref";
  const guess = () => ((navigator.language||"").toLowerCase().startsWith("zh") ? "zh" : "en");
  const getLang = () => (localStorage.getItem(LS_KEY) || guess());
  const setLang = (lang) => localStorage.setItem(LS_KEY, lang);

  function apply(lang) {
    document.documentElement.lang = lang === "zh" ? "zh-Hans" : "en";
    document.querySelectorAll("[data-i18n]").forEach(el => {
      const key = el.getAttribute("data-i18n");
      const val = dict[lang][key];
      if (val == null) return;
      el.textContent = val;
    });
    document.querySelectorAll("[data-i18n-html]").forEach(el => {
      const key = el.getAttribute("data-i18n-html");
      const val = dict[lang][key];
      if (val == null) return;
      el.innerHTML = (val || "").replace(/\n/g,"<br/>");
    });
    document.querySelectorAll("[data-lang]").forEach(b => b.classList.toggle("active", b.getAttribute("data-lang") === lang));
  }

  const path = (location.pathname.split("/").pop() || "index.html").toLowerCase();
  document.querySelectorAll(".nav a").forEach(a => {
    const href = (a.getAttribute("href") || "").toLowerCase();
    if (href === path) a.classList.add("active");
  });

  const toggle = document.querySelector("[data-nav-toggle]");
  const nav = document.querySelector(".nav");
  if (toggle && nav) toggle.addEventListener("click", () => nav.classList.toggle("open"));

  document.querySelectorAll("[data-lang]").forEach(btn => {
    btn.addEventListener("click", () => {
      const lang = btn.getAttribute("data-lang");
      setLang(lang);
      apply(lang);
    });
  });

  apply(getLang());
})();
